# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
#      flutterannotations_generator|route_builder:
#        enabled: true
#        generate_for:
#          exclude: ['**.internal.dart']
      flutterannotations_generator|annotation_write_builder:
        enabled: true
        options: { 'write': true }
        generate_for:
          exclude: ['**.internal.dart']

builders:
  annotation_write_builder:
    import: 'package:flutterannotations_generator/src/builder.dart'
    builder_factories: ['flutterAnnotationsWriteBuilder']
    build_extensions: { '.route.dart': ['.internal.dart'] }
    auto_apply: root_package
    build_to: source

#  annotation_builder:
#    import: 'package:flutterannotation/builder.dart'
#    builder_factories: ['routeBuilder']
#    build_extensions: { '.dart': ['.internal_invalid.dart'] }
#    auto_apply: root_package
#    runs_before: ['annotation_route|annotation_write_builder']
#    build_to: source
