name: flutterannotations_generator
description: Fast Flutter Development. Easy maintenance.
version: 0.0.1
author: leo<leo@biminds.cn>
homepage:  https://github.com/biminds/flutterannotations_generator.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.36.0
  build: ^1.1.3
  source_gen: ^0.9.4+2
  build_config: ^0.3.1+4
  mustache4dart: ^3.0.0-dev.0.0
  flutterannotations:
    path: ../flutterannotations
dev_dependencies:
  build_runner: ^1.3.1
  test: any
