name: flutterannotations_generator
description: >-
  Fast Flutter Development. Easy maintenance.
  Automatically generate code for converting to and from your abstract class by annotating Dart classes.
version: 1.0.0
author: Leo<leo@biminds.cn>
homepage:  https://github.com/biminds/flutter_annotations.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.36.0
  build: ^1.1.3
  source_gen: ^0.9.4+2
  build_config: ^0.3.1+4
  mustache4dart: ^3.0.0-dev.0.0
  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  flutterannotations: #^1.0.0
    path: ../flutterannotations
dev_dependencies:
  build_runner: ^1.3.1
  test: any
