name: flutterannotations_generator_example


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^2.1.0
  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  flutterannotations: #^1.0.0
    path: ../../flutterannotations
dev_dependencies:
  json_serializable: ^2.1.1
  build_runner: ^1.3.1
  flutterannotations_generator:
    path: ../../flutterannotations_generator

