name: flutterannotations
description: >-
  Fast Flutter Development. Easy maintenance.
  Automatically generate code for converting to and from your abstract class by annotating Dart classes.
version: 1.0.0
author: Leo<leo@biminds.cn>
homepage:  https://github.com/biminds/flutter_annotations.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.36.0
  #latest version  https://github.com/flutterchina/dio
  dio: ^2.1.0


